import BuilderPage from './builderPage';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { useUserData } from '../../src/hooks/useUserData';
import MultiStepPage from '../../src/components/MultiStepPage';

type BuilderProps = {
  isLoggedIn: boolean;
};

const Builder: React.FC<BuilderProps> = () => {
  const user = useUserData('user');

  const { email } = user || {};
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch({ type: 'LOGIN', payload: user });
  }, [dispatch, user, email]);

  return (
    <>
      <Head>
        <title>Visualizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BuilderPage isLoggedIn={email ? true : true} />
      <MultiStepPage />
    </>
  );
};

export default Builder;
